name: ğŸš€ Publish Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: âš“ Checkout code
        uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_ACCESS_TOKEN }}

      - name: ğŸ“‡ Get the version
        id: get_version
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          VERSION="${VERSION#v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: ğŸ¥ Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: ğŸ¯ Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: â¬‡ï¸ Install dependencies
        run: dart pub get

      - name: ğŸš€ Publish to pub.dev
        run: dart pub publish --force
